### ISSUE TITLE
A PostCSS plugin did not pass the `from` option to `postcss.parse`. 

### ISSUE THREAD

**Issue by Ivanho92** [gavinmcfarland/flex-gap-polyfill#89] opened 2024-01-27 13:25 UTC
In Astro.js, I have applied the following in `postcss.config.cjs`:

```
const postcssPresetEnv = require("postcss-preset-env");
const flexGapPolyfill = require("flex-gap-polyfill");

module.exports = {
    plugins: [postcssPresetEnv(), flexGapPolyfill()],
};
```

But when running the dev local server, it throws the following error:
`A PostCSS plugin did not pass the "from" option to "postcss.parse". This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that rai
sed this warning, please contact the package author to fix the issue.
`

Any idea how I can fix that ?

**Comment by gavinmcfarland** [comment] 2024-01-28 17:04
Hi @Ivanho92, someone else came across this issue using Vite but I couldn't work out why this error was being thrown. This plugin doesn't uses `postcss.parse` so I'm at a loss as to why this error message shows in some cases.

If you have a repo that reproduces this error I could investigate and see if there is any part of the code that's causing this error.

Many thanks, and sorry you're encountering this issue.

**Comment by Ivanho92** [comment] 2024-01-29 10:08
Hey @gavinmcfarland,

Thanks for your response! Sure the repository where I reproduced this was [this one](https://github.com/Ivanho92/website-elisegrimm).

Let me know if you have trouble reproducing the issue.

Cheers!

**Comment by gavinmcfarland** [comment] 2024-01-29 21:44
Great, thank you. Much appreciated. I'll take a look at it this weekend.

**Comment by gavinmcfarland** [comment] 2024-07-31 15:32
So I've looked into this and I believe I've narrowed it down into `postcss-values-parser` which is causing the error to happen because it uses the postcss.parser. Unfortunately I don't have a way to fix it at thee moment, but I believe it may just be a warning and shouldn't affect the plugin in any way. So for now I will mark as "wontfix". Thanks again.

**Closed by gavinmcfarland** 2024-07-31 15:32 UTC

**Comment by gavinmcfarland** [comment] 2024-08-01 12:56
Duplicate of #83
