### ISSUE TITLE
Not working with NextJS 14

### ISSUE THREAD

**Issue by mdesilva** [gavinmcfarland/flex-gap-polyfill#91] opened 2024-04-26 21:36 UTC
I'm getting the error `Error: Cannot find module 'flexGapPolyfill'` in my NextJS app.

Here is my postCSS config file:
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    'postcss-preset-env': {
      browsers: 'edge >= 18'
    },
    'flex-gap-polyfill': {},
  },
};
```

**Comment by gavinmcfarland** [comment] 2024-05-22 10:53
Hmm. Strange. Just confirm. Have you checked the module is in your `node_modules` directory?

**Comment by mdesilva** [comment] 2024-05-22 15:17
Yep, it's there.

**Comment by gavinmcfarland** [comment] 2024-06-01 16:24
Hi, sorry for only getting around to checking this.

I installed a fresh version of NextJs 14 and installed `flex-gap-polyfill`; however, I can't reproduce the issue you're experiencing.

Do you have a repo you can share?

**Comment by gavinmcfarland** [comment] 2024-08-01 17:43
Hi. I've added an [example](https://github.com/gavinmcfarland/flex-gap-polyfill/tree/master/examples/nextjs) of using the polyfill with the latest version of nextjs. Closing this issue for now. But let me know if you or anyone else has issues. Thanks again for reporting.

**Closed by gavinmcfarland** 2024-08-01 17:43 UTC
Labels: question
